title: Pensieve
name: Pensieve
email: nabarun.chatterjee@gmail.com
tagline: Whats in a tag line
description: >-
    Memory Review

url: https://nabarunchatterjee.github.io
github_username: nabarunchatterjee
timezone: Asia/Kolkata
# Build settings
markdown: kramdown
remote_theme: fongandrew/hydeout
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link: true
disqus:
    shortname: pensieve-2
author:
    name: 'Nabarun Chatterjee'

pensieve:
    repo: https://github.com/nabarunchatterjee/pensieve

twitter:
    username: vimrookie

resume: https://github.com/nabarunchatterjee/my-humble-cv/blob/master/resume.pdf
